### ISSUE TITLE
Docker container don't have permision to write data

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#1003]
hi, i had problem with installing one of container, i talked with support, he say that docker container don't have permision to write data
docker container that i cannot run properly: https://hub.docker.com/r/shellngn/pro

My OS:
```
debian@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
`Casaos  v0.4.3`

Problem 1:  i cannot acces from casaos my home directory:
![image](https://user-images.githubusercontent.com/69077240/230903435-281bf251-e68c-442f-b5a6-41ec65d23a60.png)

Folder structure:
```
debian@debian:/$ ls
443   data    etc             lib     lost+found  proc  srv  var
8034  DATA    home            lib32   media       root  sys  vmlinuz
bin   dev     initrd.img      lib64   mnt         run   tmp  vmlinuz.old
boot  errors  initrd.img.old  libx32  opt         sbin  usr  vw-data
debian@debian:/$ cd DATA/
debian@debian:/DATA$ ls
AppData  Documents  Downloads  Gallery  Media
```

Problem 2:  if i set container path `/home/node/server/data` i had error when i want to run docker container:
![image](https://user-images.githubusercontent.com/69077240/230903828-849ae52f-dee2-43d3-89f8-4526058a7fa2.png)

error:
```
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open './data/config.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at Object._0x53574d.exports. [as init] (/home/node/server/bundle.js:27:1778579)
    at Object._0x5c6688 (/home/node/server/bundle.js:1:681131)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at Object. (/home/node/server/bundle.js:27:5179148)
    at _0x272006 (/home/node/server/bundle.js:1:3567)
    at _0x5c6688 (/home/node/server/bundle.js:1:6121)
    at Object. (/home/node/server/bundle.js:1:6154)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: './data/config.json'
}
```
screen from support:
![image](https://user-images.githubusercontent.com/69077240/230904207-bc9af685-ed68-4566-8a78-c21185383b4a.png)
he can set host path  `/home/miky/Downloads/shellngn-data ` but i cannot select home directory from web interface, why?

`/DATA/AppData/shellngn` is empty, but another folders assigned to docker containers have data and containers work as expected.
I can create and delete shellngn folder using casaos file manager without problems. also i can create files inside too.

**Comment by raller1028** [comment]
Problem 1: You can manually enter the path you want to specify
Problem 2: The default path for the app installed by --mount is /var/lib/docker/volumn, which does not support modifying the installation path, we should not show that this place can be modified, next version will fix this problem

**Comment by raller1028** [comment]
![image](https://user-images.githubusercontent.com/57336867/231135953-b9be53dd-cf3c-468c-b8a8-71798bd1fa01.png)
` chmod 777 /DATA/test`
`docker run -d --name shellngn-pro --mount type=bind,source=/DATA/test,target=/home/node/server/data -p 8080:8080 -e HOST=0.0.0.0 shellngn/pro:latest`

**Comment by onlineapps-cloud** [comment]
Problem fixed using chmod 777, thanks.
