### ISSUE TITLE
[Feedback]Emby or Plex Containers do not work

### ISSUE THREAD

**Issue by bmentink** [IceWhaleTech/CasaOS#1042]
### Description

I tried installing Emby, when I opened it the webpage (8096) briefly opened, then there was a message that there was no app. Plex was the same on 32400. I installed both containers with default settings .. The only docker container I have installed successfully at the moment is FileBrowser.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 27712 
	 - Disk Used: 8634 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3763M Core:4 Linux CasaOS 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 109.0.0.0

**Comment by bmentink** [comment]
Some info from the logs:
```
Info App: File /system/plugins/OMDb.dll has version 1.0.18.0
Info App: Copying plugin from /system/plugins/OMDb.dll to /config/plugins/OMDb.dll
Error App: Error getting version number from /config/plugins/Emby.Webhooks.dll
	*** Error Report ***
	Version: 4.7.11.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.0-22-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'input')
	   at System.Version.Parse(String input)
	   at Emby.Server.Implementations.ApplicationHost.GetDllVersion(String path)
	Source: System.Private.CoreLib
	TargetSite: System.Version Parse(System.String)

```

**Comment by bmentink** [comment]
This is a "Bug" not feedback ..

**Comment by raller1028** [comment]
Emby and Plex take a while to start up properly after installation. Can you try to make sure the app is working 2 minutes after the installation is complete?

**Comment by bmentink** [comment]
No, even after 10 minutes, there is no web server available at the 8096 port.

**Comment by bmentink** [comment]
Plex and Jellyfin behave the same .... however FileBrowser, Dokuwiki and Syncthing work fine ...
Have you actually checked these containers work before adding them to the Apps? Or, are you relying on your users to "test" them for you, if the later, that is not good ..

**Comment by bmentink** [comment]
@raller1028  Any suggestions?  Can you offer suggestions to debug this?

**Comment by tigerinus** [comment]
@bmentink - would you be OK to run Emby and Plex directly from docker CLI (without CasaOS)?

Just want to rule out the possibility of any bug in CasaOS.

Also can you share logs from Plex?

**Comment by bmentink** [comment]
Ok, will try soon

**Comment by bmentink** [comment]
Logs from Plex:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** Server is unclaimed, but no claim token has been set ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Error: Unable to set up server: sqlite3_statement_backend::prepare: disk I/O error for SQL: PRAGMA cache_size=2048 (N4soci10soci_errorE)
```

**Comment by bmentink** [comment]
Seems in all cases to be File IO errors ..

**Comment by tigerinus** [comment]
> Seems in all cases to be File IO errors ..

Can we preliminarily say this is irrelevant to CasaOS per se?

**Comment by bmentink** [comment]
@tigerinus 
My setup is that the media storage is on a USB stick pool,(two disks) they are formated in XFS ..
/DATA now is a symbol link to /mnt/pool/DATA ... that should not cause this problem though, right? Other Docker containers use this pool just fine ..

**Comment by tigerinus** [comment]
That's right.

Try using some filesystem that's not XFS and not on USB stick just to keep ruling out different factors.
