### ISSUE TITLE
[Bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mariosemes** [IceWhaleTech/CasaOS#1412]
**Describe the bug**

> Getting **"panic: runtime error: invalid memory address or nil pointer dereference"** when using the casaos-cli app-management commands
```Full error:
**casaos-cli app-management set global <my-variable-here> <my-value-here>**
Global Key       Global Value
--------------   ------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4a4ef]

goroutine 1 [running]:
github.com/IceWhaleTech/CasaOS-CLI/cmd.glob..func11(0x12e03c0?, {0xc0004b2140, 0x2, 0x2?})
        /home/runner/work/CasaOS-CLI/CasaOS-CLI/cmd/appManagementSetGlobal.go:80 +0x5cf
github.com/spf13/cobra.(*Command).execute(0x12e03c0, {0xc0004b2100, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x12de700)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/IceWhaleTech/CasaOS-CLI/cmd.Execute()
        /home/runner/work/CasaOS-CLI/CasaOS-CLI/cmd/root.go:59 +0x25
main.main()
        /home/runner/work/CasaOS-CLI/CasaOS-CLI/main.go:40 +0xb4
```
**To Reproduce**

> Steps to reproduce the behavior:

1. Go to Terminal
2. run command "casaos-cli app-management list app-stores"
3. or run command "casaos-cli app-management list apps"
4. or run command "casaos-cli app-management set global variable value"

**Expected behavior**

> Expected per steps:
2. Get a list of app-stores
3. Get a list of installed apps
4. Create a global environment variable for docker

**Desktop (please complete the following information):**

```
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
```

**System Time**

> Run `timedatectl` and share the output

```
 Local time: Sun 2023-09-24 15:27:06 UTC
           Universal time: Sun 2023-09-24 15:27:06 UTC
                 RTC time: Sun 2023-09-24 15:27:05
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

[casaos-gateway.log](https://github.com/IceWhaleTech/CasaOS/files/12708904/casaos-gateway.log)
[casaos-service.log](https://github.com/IceWhaleTech/CasaOS/files/12708905/casaos-service.log)
[casaos-app-management.log](https://github.com/IceWhaleTech/CasaOS/files/12708906/casaos-app-management.log)
[casaos-local-storage.log](https://github.com/IceWhaleTech/CasaOS/files/12708907/casaos-local-storage.log)
[casaos-user-service.log](https://github.com/IceWhaleTech/CasaOS/files/12708908/casaos-user-service.log)

**Additional context**

> Had a longer support session with your community mod Dragonfire1119 who tried everything to figure out the reason why I'm getting this issue. Before this moment, I was on the same machine on a Ubuntu 22.04 installation and had the same problems, regarding that issue, Dragon suggested to try and install a newer OS. And here we are, sadly again.

Some steps that we tried to eliminate the issue:

**a. -----------------------------------------**
When the Panic is trigger, there is nothing visible in:
```journalctl -u casaos-app-management.service```

**b. -----------------------------------------** 
1. Edit ```sudo nano /lib/systemd/system/casaos-app-management.service```
2. Add ```StandardOutput=append:/var/log/casaos-app-management.stdout
StandardError=append:/var/log/casaos-app-management.stderr```
3. Run ```sudo systemctl daemon-reload```
4. Run ```sudo systemctl restart casaos-app-management.service```
**Result:** Nothing

**c. -----------------------------------------**
1. Run ```sudo systemctl stop casaos-app-management.service```
2. Run while forcing a Panic ```/usr/bin/casaos-app-management -c /etc/casaos/app-management.conf 2> error_log.txt```
**Result:**
```
git commit: cda78104f41269823a29f5a0ccf962d23269a1a5
build date: 2023-09-01T10:30:36Z
panic: open /var/run/casaos/management.url: permission denied
goroutine 1 [running]:
github.com/IceWhaleTech/CasaOS-AppManagement/service.NewService({0xc000b0c349, 0xf})
    /home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/service.go:48 +0x1e5
main.main()
    /home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/main.go:67 +0x265
```

**d. -----------------------------------------**
Run ```ls -lsa /var/run/casaos```
**Result:** 
```
total 132
  0 drwxr-xr-x  2 root root    200 Sep 24 13:53 .
  0 drwxr-xr-x 34 root root    980 Sep 24 14:01 ..
  4 -rw-r--r--  1 root root     22 Sep 24 13:53 casaos.url
  4 -rw-------  1 root root      5 Sep 24 13:53 gateway.pid
  4 -rw-------  1 root root     22 Sep 24 13:53 management.url
104 -rw-r--r--  1 root root 106496 Sep 24 13:53 message-bus.db
  4 -rw-------  1 root root     22 Sep 24 13:53 message-bus.url
  4 -rw-------  1 root root   1384 Sep 24 14:22 routes.json
  4 -rw-------  1 root root     22 Sep 24 13:53 static.url
  4 -rw-------  1 root root     22 Sep 24 13:53 user-service.url
```

**e. -----------------------------------------**
Run ```sudo chmod 644 /var/run/casaos/management.url```
**Result:** Panic still here

**f. -----------------------------------------**
1. Run ```sudo nano /lib/systemd/system/casaos-app-management.service```
2. Add ```User=root
Group=root``` under [Service]
3. Run ```sudo systemctl daemon-reload
sudo systemctl restart casaos-app-management.service```
**Result:** Still the same panic on the same commands

**g. -----------------------------------------**
1. Run ```sudo chmod -R 775 /var/log/casaos/```
2. Run ```sudo chown -R root:root /var/log/casaos/```
**Result:** Still the same panic on the same commands

**Comment by CorrectRoadH** [comment]
Are you still having this problem? We can't reproduce it👀

**Comment by fboaventura** [comment]
I have the same issue, behavior, and symptoms as the OP. I can't add, remove, or update anything related to the app stores, although it is still possible to install new apps from the ones already listed, but without updates. It also seems related to #1493 because that was what first caught my attention.

```
CasaOS: 0.4.4.2
OS: Ubuntu Linux 22.04.3 LTS
Browser: Chrome Version 118.0.5993.117 (Build officiel) (arm64)
         Safari Version 17.1 (19616.2.9.11.7)
         Brave [Version 1.60.114 Chromium: 119.0.6045.124 (Build officiel) (arm64)]
```

`timedatectl`
```
               Local time: dom 2023-11-12 23:00:36 UTC
           Universal time: dom 2023-11-12 23:00:36 UTC
                 RTC time: dom 2023-11-12 23:00:36
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
