### ISSUE TITLE
[Vultr] Fails on fresh install of Debian 11

### ISSUE THREAD

**Issue by kobykotiv** [IceWhaleTech/CasaOS#434]
**Describe the bug**
I cannot get this to work on vultr the same way I can on Digital Ocean.

**To Reproduce**
- Spin up a new Debian instance on vultr
- Run the Casaos install script
- RUN `casaos`

**Expected behavior**
Casaos is supposed to show me an ip address to connect to. But instead I'm given this sqlite error. 

Logs

```bash
2022/08/07 02:18:18 /source/pkg/sqlite/db.go:46 no such table: o_user
[0.042ms] [rows:0] alter table o_user rename to old_user;

        create table o_users ( id integer primary key,username text,password text,role text,email text,nickname text,avatar text,description text,created_at datetime,updated_at datetime);

        insert into o_users select id,user_name,password,role,email,nick_name,avatar,description,created_at,updated_at from old_user;

        drop table old_user;
        drop table o_user;

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

2022/08/07 02:18:19 listen tcp :45079: bind: address already in use
panic: listen tcp :45079: bind: address already in use

goroutine 32 [running]:
log.Panic({0xc000061d50, 0x280d518, 0x1})
        /usr/local/go/src/log/log.go:354 +0x65
github.com/ambelovsky/gosf.startHTTPServer(0x15e21e0, 0x0, {0xc0001fe626, 0x6}, 0xc000061db8, {0x280d518, 0x1})
        /go/pkg/mod/github.com/ambelovsky/gosf@v0.0.0-20201109201340-237aea4d6109/main.go:117 +0x185
github.com/ambelovsky/gosf.Startup(0x15e21e0)
        /go/pkg/mod/github.com/ambelovsky/gosf@v0.0.0-20201109201340-237aea4d6109/main.go:77 +0x526
github.com/IceWhaleTech/CasaOS/route.SocketInit(0xc0003ca5a0)
        /source/route/socket.go:57 +0x30f
created by main.main
        /source/main.go:83 +0x3c5
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23111682/183272382-2c26175f-31fa-4177-b147-c4e185487556.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 103
 - OS: Debian 11
 - OS: ChromeOS 103

**Comment by LinkLeong** [comment]
You need to change the HttpPort in /etc/casaos.conf to an unoccupied port

**Comment by LinkLeong** [comment]
We will close this issue, if you still have problems please reopen Issus
